project:
  type: book

book:
  title: "Bioarchaeology Visualization"
  author: "Jen Heilmann"
  date: "9/26/2026"
  chapters:
    - index.qmd
    - intro_visual.qmd
    - part: sisotopes.qmd
      chapters:
        - isodata.qmd
        - trace.qmd
        - heavy.qmd
        - light.qmd
    - part: geomorph.qmd
      chapters:
        - GPA.qmd
        - PCA.qmd
    - part: mapping.qmd
      chapters:
        - map.qmd
        - choropleth.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    link-external-newwindow: true
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto