# Types of Visualizations

## Distribution

```{r}
library(ggplot2)
data <- data.frame(value=rnorm(100, mean=15, sd=3))
data$group <- as.factor(sample(1:3, size=100, replace=TRUE))
```

### Boxplot

```{r}
#| label: basic-boxplot
#| fig-cap: "Basic Boxplot"

ggplot(data, aes(y=value))+
  geom_boxplot()
```

```{r}
#| label: group-boxplot
#| fig-cap: "Boxplot by Group"

ggplot(data, aes(y=value, x=group))+
  geom_boxplot()
```

### Violin

```{r}
#| label: violin
#| fig-cap: "Violin Plot by Group"
ggplot(data, aes(x=group, y=value))+
  geom_violin()
```

### Histogram

```{r}
#| label: basic-histogram
#| fig-cap: "Basic Histogram"
#| message: false

ggplot(data, aes(x=value))+
  geom_histogram()
```

```{r}
#| label: bin-histogram
#| fig-cap: "Histogram with designated Bins"

ggplot(data, aes(x=value))+
  geom_histogram(binwidth=.1)
```

### Density

```{r}
#| label: density

ggplot(data, aes(x=value))+
  geom_density()
```

## Correlation

### Scatter

### Bubble

### Heatmap

### Correlogram

## Map

### Map

### Choropleth

### Bubble Map

## Flow

### Chord Diagram

### Network

### Sankey

### Dendrogram
